### ISSUE TITLE
Plugin: Config file merging

### ISSUE THREAD

**Issue by PEMapModder** [Gamecrafter/PocketMine-Plugins#1]
I noticed that you are overwriting the config file if the plugin is updated, which will reset all configurations. Consider updating the code in a way such that you can merge the config file with a new version, e.g. appending missing fields directly into the file.

**Comment by Gamecrafter** [comment]
@PEMapModder That would actually be a pretty good feature. I just noticed that there are no plugins that do this. Thanks for the suggestion, I'll implement that soon.

**Comment by Gamecrafter** [comment]
I might remove the automatic config updating altogether in the future. I find it easier to just manually remove your config file.
