### ISSUE TITLE
where is rocketpads

### ISSUE THREAD

**Issue by CraftingMania** [Gamecrafter/PocketMine-Plugins#2]
i cant find then phar since asparanc forum stoped please send me phar

**Comment by CraftingMania** [comment]
pocketmine forums name: amir emad

**Comment by Gamecrafter** [comment]
@CraftingMania Before you create an issue, please look around. There are many places you can still find them. You can find them in some of these repos: https://github.com/Gamecrafter/PocketMine-Plugins/network/members
