### ISSUE TITLE
How to Hide Commands on /help with RapidCMD?

### ISSUE THREAD

**Issue by ZhenMC** [Gamecrafter/PocketMine-Plugins#3]
Is there a way to hide command on Help.

**Comment by Gamecrafter** [comment]
@ZhenMC RapidCMD is far from ready(not too far, but not too near, either). But I have another plugin in another repo that will suit your needs: https://github.com/Gamecrafter/PocketMine-Script-Plugins/blob/master/HelpTailor.php Just download the file and drop it into your plugin directory.
